global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: '/metrics'

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:8001']
    metrics_path: '/metrics'

  - job_name: 'subscription_service'
    static_configs:
      - targets: ['subscription_service:8002']
    metrics_path: '/metrics'

  - job_name: 'partner_service'
    static_configs:
      - targets: ['partner_service:8003']
    metrics_path: '/metrics'

  - job_name: 'visit_service'
    static_configs:
      - targets: ['visit_service:8004']
    metrics_path: '/metrics'

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment_service:8005']
    metrics_path: '/metrics'

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:8006']
    metrics_path: '/metrics'

  - job_name: 'admin_service'
    static_configs:
      - targets: ['admin_service:8007']
    metrics_path: '/metrics'
